# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:Router1 => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.12.1', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "r12-net"},
                   {ip: '192.168.13.1', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "r13-net"},
                ]
  },


  :Router2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.12.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "r12-net"},
                   {ip: '192.168.23.2', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "r23-net"},
                ]
  },

  :Router3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.13.3', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "r13-net"},
                   {ip: '192.168.23.3', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "r23-net"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "Router1"
          box.vm.provision :ansible do |ansible|
          ansible.playbook = "router1/ans_pl.yml"
        end
        when "Router2"
          box.vm.provision :ansible do |ansible|
          ansible.playbook = "router2/ans_pl.yml"
        end
        when "Router3"
          box.vm.provision :ansible do |ansible|
          ansible.playbook = "router3/ans_pl.yml"

        end
       end

      end

  end
  
  
end