# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :client => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "dir-net"},
                ]
  },
  :server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "dir-net"},
                ]
  },
  
  
 
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y epel-release
          yum install -y openvpn easy-rsa tcpdump
          setenforce 0
        SHELL
        
        case boxname.to_s
        
        when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          sed -i 's/^PasswordAuthentication\ no/PasswordAuthentication\ yes/' /etc/ssh/sshd_config
          chown :vagrant /etc/openvpn/
          chmod g+w /etc/openvpn/
          systemctl restart sshd
          cp /vagrant/client.conf /etc/openvpn/client.conf
          
          SHELL
        
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sshpass -y
          cd /etc/openvpn/
          /usr/share/easy-rsa/3.0.3/easyrsa init-pki
          echo 'rasvpn' | /usr/share/easy-rsa/3.0.3/easyrsa build-ca nopass
          echo 'rasvpn' | /usr/share/easy-rsa/3.0.3/easyrsa gen-req server nopass
          echo 'yes' | /usr/share/easy-rsa/3.0.3/easyrsa sign-req server server
          /usr/share/easy-rsa/3.0.3/easyrsa gen-dh
          openvpn --genkey --secret ta.key
          echo 'client' | /usr/share/easy-rsa/3/easyrsa gen-req client nopass
          echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req client client
          cp /vagrant/server.conf /etc/openvpn/server.conf
          echo 'iroute 192.168.33.0 255.255.255.0' > /etc/openvpn/client/client
          systemctl start openvpn@server
          sshpass -v -p vagrant scp -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no /etc/openvpn/pki/ca.crt vagrant@192.168.255.1:/etc/openvpn/ca.crt
          sshpass -v -p vagrant scp -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no /etc/openvpn/pki/issued/client.crt vagrant@192.168.255.1:/etc/openvpn/client.crt
          sshpass -v -p vagrant scp -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no /etc/openvpn/pki/private/client.key vagrant@192.168.255.1:/etc/openvpn/client.key
          SHELL
        end

      end

  end
  
  
end

