# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV['HOME']

MACHINES = {
  :otuslinux => {
                  :box_name => "centos/7",
                  :ip_addr => '192.168.11.101',
                },
            }

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false

          end
 	  box.vm.provision "shell", inline: <<-SHELL
        #default
	      mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        #install packages we need
	      yum install -y redhat-lsb-core wget rpmdevtools rpm-build createrepo yum-utils epel-release gcc
        #delete current version of wget
        rpm -e wget
        #download and unpack source rpm
        cd /opt/
        yumdownloader --source wget
        rpm -i wget-1.14-18.el7_6.1.src.rpm
        #install dependancies based on spec file and build rpm
        cd /root/
        yum-builddep rpmbuild/SPECS/wget.spec -y
        rpmbuild -bb rpmbuild/SPECS/wget.spec

        #creating repo
        sudo mkdir -p /opt/repos/CentOS/7/
        sudo createrepo /opt/repos/CentOS/7/
        echo "[local-base]" > /etc/yum.repos.d/local.repo
        echo "name=Local-Base" >> /etc/yum.repos.d/local.repo
        echo "baseurl=file:///opt/repos/CentOS/7/" >> /etc/yum.repos.d/local.repo
        echo "enabled=1" >> /etc/yum.repos.d/local.repo
        echo "gpgcheck=0" >> /etc/yum.repos.d/local.repo
        mv /root/rpmbuild/RPMS/x86_64/wget-1.14-18.el7.1.x86_64.rpm /opt/repos/CentOS/7/wget-1.14-18.el7.1.x86_64.rpm
        sudo createrepo /opt/repos/CentOS/7/
        
        #install wget from local-base repo
        #yum install --disablerepo=* --enablerepo=local-base wget -y
  	  SHELL

      end
  end
end

