# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :client => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.254.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "dir-net2"},
                ]
  },
  :server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.254.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "dir-net2"},
                ]
  },
  
  
 
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y epel-release
          yum install -y openvpn iperf3 tcpdump
          setenforce 0
        SHELL
        
        case boxname.to_s
        
        when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          sed -i 's/^PasswordAuthentication\ no/PasswordAuthentication\ yes/' /etc/ssh/sshd_config
          chown :vagrant /etc/openvpn/
          chmod g+w /etc/openvpn/
          systemctl restart sshd
          cp /vagrant/client-tun.conf /etc/openvpn/client-tun.conf
          cp /vagrant/client-tap.conf /etc/openvpn/client-tap.conf
          SHELL
        
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sshpass -y
          openvpn --genkey --secret /etc/openvpn/static.key
          sshpass -v -p vagrant scp -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no /etc/openvpn/static.key vagrant@192.168.255.1:/etc/openvpn/static.key
          cp /vagrant/server-tun.conf /etc/openvpn/server-tun.conf
          cp /vagrant/server-tap.conf /etc/openvpn/server-tap.conf
          systemctl start openvpn@server-tun
          systemctl start openvpn@server-tap
          systemctl enable openvpn@server-tun
          iperf3 -Ds
          SHELL
        end

      end

  end
  
  
end

