---
# tasks file for web-server
- name: Install epel-release
  yum:
   name: epel-release
   state: latest

- name: Install nginx
  yum:
   name: nginx
   state: latest

- name: Change web server's port
  template:
   src: etc/nginx/nginx.conf.j2
   dest: /etc/nginx/nginx.conf
   owner: root
   group: root
   mode: 0644
  notify: 
   - nginx start
   - nginx enabled
